# Generated by Django 5.0.3 on 2024-07-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedula_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
